package com.ishireader.app.ui.shelves

/** Emoji choices for a shelf icon, ported from the website's SHELF_ICON_CHOICES
 *  (shelfIcons.ts) so both clients offer the identical picker. */
data class ShelfIconChoice(val icon: String, val label: String)

val SHELF_ICON_CHOICES: List<ShelfIconChoice> = listOf(
    // Smileys & emotion
    ShelfIconChoice("😀", "Grinning face"),
    ShelfIconChoice("😃", "Grinning face with big eyes"),
    ShelfIconChoice("😄", "Grinning face with smiling eyes"),
    ShelfIconChoice("😁", "Beaming face with smiling eyes"),
    ShelfIconChoice("😆", "Grinning squinting face"),
    ShelfIconChoice("😅", "Grinning face with sweat"),
    ShelfIconChoice("🤣", "Rolling on the floor laughing"),
    ShelfIconChoice("😂", "Face with tears of joy"),
    ShelfIconChoice("🙂", "Slightly smiling face"),
    ShelfIconChoice("🙃", "Upside-down face"),
    ShelfIconChoice("😉", "Winking face"),
    ShelfIconChoice("😊", "Smiling face with smiling eyes"),
    ShelfIconChoice("😇", "Smiling face with halo"),
    ShelfIconChoice("🥰", "Smiling face with hearts"),
    ShelfIconChoice("😍", "Smiling face with heart-eyes"),
    ShelfIconChoice("🤩", "Star-struck"),
    ShelfIconChoice("😘", "Face blowing a kiss"),
    ShelfIconChoice("😗", "Kissing face"),
    ShelfIconChoice("☺️", "Smiling face"),
    ShelfIconChoice("😚", "Kissing face with closed eyes"),
    ShelfIconChoice("😙", "Kissing face with smiling eyes"),
    ShelfIconChoice("🥲", "Smiling face with tear"),
    ShelfIconChoice("😋", "Face savoring food"),
    ShelfIconChoice("😛", "Face with tongue"),
    ShelfIconChoice("😜", "Winking face with tongue"),
    ShelfIconChoice("🤪", "Zany face"),
    ShelfIconChoice("😝", "Squinting face with tongue"),
    ShelfIconChoice("🤑", "Money-mouth face"),
    ShelfIconChoice("🤗", "Smiling face with open hands"),
    ShelfIconChoice("🤭", "Face with hand over mouth"),
    ShelfIconChoice("🤫", "Shushing face"),
    ShelfIconChoice("🤔", "Thinking face"),
    ShelfIconChoice("🤐", "Zipper-mouth face"),
    ShelfIconChoice("🤨", "Face with raised eyebrow"),
    ShelfIconChoice("😐", "Neutral face"),
    ShelfIconChoice("😑", "Expressionless face"),
    ShelfIconChoice("😶", "Face without mouth"),
    ShelfIconChoice("😏", "Smirking face"),
    ShelfIconChoice("😒", "Unamused face"),
    ShelfIconChoice("🙄", "Face with rolling eyes"),
    ShelfIconChoice("😬", "Grimacing face"),
    ShelfIconChoice("🤥", "Lying face"),
    ShelfIconChoice("😌", "Relieved face"),
    ShelfIconChoice("😔", "Pensive face"),
    ShelfIconChoice("😪", "Sleepy face"),
    ShelfIconChoice("🤤", "Drooling face"),
    ShelfIconChoice("😴", "Sleeping face"),
    ShelfIconChoice("😷", "Face with medical mask"),
    ShelfIconChoice("🤒", "Face with thermometer"),
    ShelfIconChoice("🤕", "Face with head-bandage"),
    ShelfIconChoice("🤢", "Nauseated face"),
    ShelfIconChoice("🤮", "Face vomiting"),
    ShelfIconChoice("🤧", "Sneezing face"),
    ShelfIconChoice("🥵", "Hot face"),
    ShelfIconChoice("🥶", "Cold face"),
    ShelfIconChoice("🥴", "Woozy face"),
    ShelfIconChoice("😵", "Dizzy face"),
    ShelfIconChoice("🤯", "Exploding head"),
    ShelfIconChoice("🤠", "Cowboy hat face"),
    ShelfIconChoice("🥳", "Partying face"),
    ShelfIconChoice("🥸", "Disguised face"),
    ShelfIconChoice("😎", "Smiling face with sunglasses"),
    ShelfIconChoice("🤓", "Nerd face"),
    ShelfIconChoice("🧐", "Face with monocle"),
    ShelfIconChoice("😕", "Confused face"),
    ShelfIconChoice("😟", "Worried face"),
    ShelfIconChoice("🙁", "Slightly frowning face"),
    ShelfIconChoice("☹️", "Frowning face"),
    ShelfIconChoice("😮", "Face with open mouth"),
    ShelfIconChoice("😯", "Hushed face"),
    ShelfIconChoice("😲", "Astonished face"),
    ShelfIconChoice("😳", "Flushed face"),
    ShelfIconChoice("🥺", "Pleading face"),
    ShelfIconChoice("😦", "Frowning face with open mouth"),
    ShelfIconChoice("😧", "Anguished face"),
    ShelfIconChoice("😨", "Fearful face"),
    ShelfIconChoice("😰", "Anxious face with sweat"),
    ShelfIconChoice("😥", "Sad but relieved face"),
    ShelfIconChoice("😢", "Crying face"),
    ShelfIconChoice("😭", "Loudly crying face"),
    ShelfIconChoice("😱", "Face screaming in fear"),
    ShelfIconChoice("😖", "Confounded face"),
    ShelfIconChoice("😣", "Persevering face"),
    ShelfIconChoice("😞", "Disappointed face"),
    ShelfIconChoice("😓", "Downcast face with sweat"),
    ShelfIconChoice("😩", "Weary face"),
    ShelfIconChoice("😫", "Tired face"),
    ShelfIconChoice("🥱", "Yawning face"),
    ShelfIconChoice("😤", "Face with steam from nose"),
    ShelfIconChoice("😡", "Pouting face"),
    ShelfIconChoice("😠", "Angry face"),
    ShelfIconChoice("🤬", "Face with symbols on mouth"),
    ShelfIconChoice("😈", "Smiling face with horns"),
    ShelfIconChoice("👿", "Angry face with horns"),
    ShelfIconChoice("💀", "Skull"),
    ShelfIconChoice("☠️", "Skull and crossbones"),
    ShelfIconChoice("🤡", "Clown face"),
    ShelfIconChoice("👹", "Ogre"),
    ShelfIconChoice("👺", "Goblin"),
    ShelfIconChoice("👻", "Ghost"),
    ShelfIconChoice("👽", "Alien"),
    ShelfIconChoice("👾", "Alien monster"),
    ShelfIconChoice("🤖", "Robot"),

    // Hearts
    ShelfIconChoice("❤️", "Red heart"),
    ShelfIconChoice("🧡", "Orange heart"),
    ShelfIconChoice("💛", "Yellow heart"),
    ShelfIconChoice("💚", "Green heart"),
    ShelfIconChoice("💙", "Blue heart"),
    ShelfIconChoice("💜", "Purple heart"),
    ShelfIconChoice("🖤", "Black heart"),
    ShelfIconChoice("🤍", "White heart"),
    ShelfIconChoice("🤎", "Brown heart"),
    ShelfIconChoice("💔", "Broken heart"),
    ShelfIconChoice("❣️", "Heart exclamation"),
    ShelfIconChoice("💕", "Two hearts"),
    ShelfIconChoice("💞", "Revolving hearts"),
    ShelfIconChoice("💓", "Beating heart"),
    ShelfIconChoice("💗", "Growing heart"),
    ShelfIconChoice("💖", "Sparkling heart"),
    ShelfIconChoice("💘", "Heart with arrow"),
    ShelfIconChoice("💝", "Heart with ribbon"),
    ShelfIconChoice("💟", "Heart decoration"),

    // Hand gestures
    ShelfIconChoice("👋", "Waving hand"),
    ShelfIconChoice("🤚", "Raised back of hand"),
    ShelfIconChoice("🖐️", "Hand with fingers splayed"),
    ShelfIconChoice("✋", "Raised hand"),
    ShelfIconChoice("🖖", "Vulcan salute"),
    ShelfIconChoice("👌", "OK hand"),
    ShelfIconChoice("🤌", "Pinched fingers"),
    ShelfIconChoice("🤏", "Pinching hand"),
    ShelfIconChoice("✌️", "Victory hand"),
    ShelfIconChoice("🤞", "Crossed fingers"),
    ShelfIconChoice("🤟", "Love-you gesture"),
    ShelfIconChoice("🤘", "Sign of the horns"),
    ShelfIconChoice("🤙", "Call me hand"),
    ShelfIconChoice("👈", "Backhand index pointing left"),
    ShelfIconChoice("👉", "Backhand index pointing right"),
    ShelfIconChoice("👆", "Backhand index pointing up"),
    ShelfIconChoice("🖕", "Middle finger"),
    ShelfIconChoice("👇", "Backhand index pointing down"),
    ShelfIconChoice("☝️", "Index pointing up"),
    ShelfIconChoice("👍", "Thumbs up"),
    ShelfIconChoice("👎", "Thumbs down"),
    ShelfIconChoice("✊", "Raised fist"),
    ShelfIconChoice("👊", "Oncoming fist"),
    ShelfIconChoice("👏", "Clapping hands"),
    ShelfIconChoice("🙌", "Raising hands"),
    ShelfIconChoice("👐", "Open hands"),
    ShelfIconChoice("🤲", "Palms up together"),
    ShelfIconChoice("🤝", "Handshake"),
    ShelfIconChoice("🙏", "Folded hands"),
    ShelfIconChoice("✍️", "Writing hand"),
    ShelfIconChoice("💅", "Nail polish"),
    ShelfIconChoice("💪", "Flexed biceps"),

    // Animals & nature
    ShelfIconChoice("🐶", "Dog face"),
    ShelfIconChoice("🐱", "Cat face"),
    ShelfIconChoice("🐭", "Mouse face"),
    ShelfIconChoice("🐹", "Hamster"),
    ShelfIconChoice("🐰", "Rabbit face"),
    ShelfIconChoice("🦊", "Fox"),
    ShelfIconChoice("🐻", "Bear"),
    ShelfIconChoice("🐼", "Panda"),
    ShelfIconChoice("🐨", "Koala"),
    ShelfIconChoice("🐯", "Tiger face"),
    ShelfIconChoice("🦁", "Lion"),
    ShelfIconChoice("🐮", "Cow face"),
    ShelfIconChoice("🐷", "Pig face"),
    ShelfIconChoice("🐸", "Frog"),
    ShelfIconChoice("🐵", "Monkey face"),
    ShelfIconChoice("🐔", "Chicken"),
    ShelfIconChoice("🐧", "Penguin"),
    ShelfIconChoice("🐦", "Bird"),
    ShelfIconChoice("🦆", "Duck"),
    ShelfIconChoice("🦉", "Owl"),
    ShelfIconChoice("🦇", "Bat"),
    ShelfIconChoice("🐺", "Wolf"),
    ShelfIconChoice("🐗", "Boar"),
    ShelfIconChoice("🐴", "Horse face"),
    ShelfIconChoice("🦄", "Unicorn"),
    ShelfIconChoice("🐝", "Honeybee"),
    ShelfIconChoice("🦋", "Butterfly"),
    ShelfIconChoice("🐌", "Snail"),
    ShelfIconChoice("🐞", "Lady beetle"),
    ShelfIconChoice("🐢", "Turtle"),
    ShelfIconChoice("🐍", "Snake"),
    ShelfIconChoice("🦎", "Lizard"),
    ShelfIconChoice("🦖", "T-Rex"),
    ShelfIconChoice("🐙", "Octopus"),
    ShelfIconChoice("🦑", "Squid"),
    ShelfIconChoice("🦀", "Crab"),
    ShelfIconChoice("🐠", "Tropical fish"),
    ShelfIconChoice("🐟", "Fish"),
    ShelfIconChoice("🐬", "Dolphin"),
    ShelfIconChoice("🐳", "Spouting whale"),
    ShelfIconChoice("🦈", "Shark"),
    ShelfIconChoice("🐅", "Tiger"),
    ShelfIconChoice("🦓", "Zebra"),
    ShelfIconChoice("🦍", "Gorilla"),
    ShelfIconChoice("🐘", "Elephant"),
    ShelfIconChoice("🦛", "Hippopotamus"),
    ShelfIconChoice("🐪", "Camel"),
    ShelfIconChoice("🦒", "Giraffe"),
    ShelfIconChoice("🐐", "Goat"),
    ShelfIconChoice("🦌", "Deer"),
    ShelfIconChoice("🐕", "Dog"),
    ShelfIconChoice("🐈", "Cat"),
    ShelfIconChoice("🦃", "Turkey"),
    ShelfIconChoice("🕊️", "Dove"),
    ShelfIconChoice("🐇", "Rabbit"),
    ShelfIconChoice("🐿️", "Chipmunk"),
    ShelfIconChoice("🦔", "Hedgehog"),
    ShelfIconChoice("🐉", "Dragon"),
    ShelfIconChoice("🌵", "Cactus"),
    ShelfIconChoice("🎄", "Christmas tree"),
    ShelfIconChoice("🌲", "Evergreen tree"),
    ShelfIconChoice("🌳", "Deciduous tree"),
    ShelfIconChoice("🌴", "Palm tree"),
    ShelfIconChoice("🌱", "Seedling"),
    ShelfIconChoice("🌿", "Herb"),
    ShelfIconChoice("☘️", "Shamrock"),
    ShelfIconChoice("🍀", "Four leaf clover"),
    ShelfIconChoice("🍁", "Maple leaf"),
    ShelfIconChoice("🍄", "Mushroom"),
    ShelfIconChoice("🌾", "Sheaf of rice"),
    ShelfIconChoice("🌷", "Tulip"),
    ShelfIconChoice("🌹", "Rose"),
    ShelfIconChoice("🌺", "Hibiscus"),
    ShelfIconChoice("🌸", "Cherry blossom"),
    ShelfIconChoice("🌼", "Blossom"),
    ShelfIconChoice("🌻", "Sunflower"),
    ShelfIconChoice("🌞", "Sun with face"),
    ShelfIconChoice("🌝", "Full moon with face"),
    ShelfIconChoice("🌙", "Crescent moon"),
    ShelfIconChoice("🌎", "Globe showing Americas"),
    ShelfIconChoice("🌍", "Globe showing Europe-Africa"),
    ShelfIconChoice("🌏", "Globe showing Asia-Australia"),
    ShelfIconChoice("💫", "Dizzy star"),
    ShelfIconChoice("🌟", "Glowing star"),
    ShelfIconChoice("✨", "Sparkles"),
    ShelfIconChoice("⚡", "High voltage"),
    ShelfIconChoice("☄️", "Comet"),
    ShelfIconChoice("💥", "Collision"),
    ShelfIconChoice("🔥", "Fire"),
    ShelfIconChoice("🌪️", "Tornado"),
    ShelfIconChoice("🌈", "Rainbow"),
    ShelfIconChoice("☀️", "Sun"),
    ShelfIconChoice("⛅", "Sun behind cloud"),
    ShelfIconChoice("☁️", "Cloud"),
    ShelfIconChoice("🌧️", "Cloud with rain"),
    ShelfIconChoice("⛈️", "Cloud with lightning and rain"),
    ShelfIconChoice("❄️", "Snowflake"),
    ShelfIconChoice("☃️", "Snowman"),
    ShelfIconChoice("💧", "Droplet"),
    ShelfIconChoice("🌊", "Water wave"),

    // Food & drink
    ShelfIconChoice("🍏", "Green apple"),
    ShelfIconChoice("🍎", "Red apple"),
    ShelfIconChoice("🍐", "Pear"),
    ShelfIconChoice("🍊", "Tangerine"),
    ShelfIconChoice("🍋", "Lemon"),
    ShelfIconChoice("🍌", "Banana"),
    ShelfIconChoice("🍉", "Watermelon"),
    ShelfIconChoice("🍇", "Grapes"),
    ShelfIconChoice("🍓", "Strawberry"),
    ShelfIconChoice("🫐", "Blueberries"),
    ShelfIconChoice("🍈", "Melon"),
    ShelfIconChoice("🍒", "Cherries"),
    ShelfIconChoice("🍑", "Peach"),
    ShelfIconChoice("🥭", "Mango"),
    ShelfIconChoice("🍍", "Pineapple"),
    ShelfIconChoice("🥥", "Coconut"),
    ShelfIconChoice("🥝", "Kiwi fruit"),
    ShelfIconChoice("🍅", "Tomato"),
    ShelfIconChoice("🥑", "Avocado"),
    ShelfIconChoice("🥦", "Broccoli"),
    ShelfIconChoice("🥬", "Leafy green"),
    ShelfIconChoice("🥒", "Cucumber"),
    ShelfIconChoice("🌶️", "Hot pepper"),
    ShelfIconChoice("🌽", "Ear of corn"),
    ShelfIconChoice("🥕", "Carrot"),
    ShelfIconChoice("🧄", "Garlic"),
    ShelfIconChoice("🧅", "Onion"),
    ShelfIconChoice("🥔", "Potato"),
    ShelfIconChoice("🍠", "Roasted sweet potato"),
    ShelfIconChoice("🥐", "Croissant"),
    ShelfIconChoice("🍞", "Bread"),
    ShelfIconChoice("🥖", "Baguette bread"),
    ShelfIconChoice("🧀", "Cheese wedge"),
    ShelfIconChoice("🥚", "Egg"),
    ShelfIconChoice("🍳", "Fried egg"),
    ShelfIconChoice("🥞", "Pancakes"),
    ShelfIconChoice("🧇", "Waffle"),
    ShelfIconChoice("🥓", "Bacon"),
    ShelfIconChoice("🍗", "Poultry leg"),
    ShelfIconChoice("🍔", "Hamburger"),
    ShelfIconChoice("🍟", "French fries"),
    ShelfIconChoice("🍕", "Pizza"),
    ShelfIconChoice("🌭", "Hot dog"),
    ShelfIconChoice("🌮", "Taco"),
    ShelfIconChoice("🌯", "Burrito"),
    ShelfIconChoice("🥗", "Green salad"),
    ShelfIconChoice("🍝", "Spaghetti"),
    ShelfIconChoice("🍜", "Steaming bowl"),
    ShelfIconChoice("🍲", "Pot of food"),
    ShelfIconChoice("🍣", "Sushi"),
    ShelfIconChoice("🍱", "Bento box"),
    ShelfIconChoice("🍤", "Fried shrimp"),
    ShelfIconChoice("🍙", "Rice ball"),
    ShelfIconChoice("🍚", "Cooked rice"),
    ShelfIconChoice("🍦", "Soft ice cream"),
    ShelfIconChoice("🍩", "Doughnut"),
    ShelfIconChoice("🍪", "Cookie"),
    ShelfIconChoice("🎂", "Birthday cake"),
    ShelfIconChoice("🍰", "Shortcake"),
    ShelfIconChoice("🧁", "Cupcake"),
    ShelfIconChoice("🍫", "Chocolate bar"),
    ShelfIconChoice("🍬", "Candy"),
    ShelfIconChoice("🍭", "Lollipop"),
    ShelfIconChoice("🍯", "Honey pot"),
    ShelfIconChoice("🥛", "Glass of milk"),
    ShelfIconChoice("☕", "Hot beverage"),
    ShelfIconChoice("🍵", "Teacup without handle"),
    ShelfIconChoice("🍶", "Sake"),
    ShelfIconChoice("🍺", "Beer mug"),
    ShelfIconChoice("🍷", "Wine glass"),
    ShelfIconChoice("🍸", "Cocktail glass"),
    ShelfIconChoice("🍹", "Tropical drink"),
    ShelfIconChoice("🍾", "Bottle with popping cork"),

    // Activities & sports
    ShelfIconChoice("⚽", "Soccer ball"),
    ShelfIconChoice("🏀", "Basketball"),
    ShelfIconChoice("🏈", "American football"),
    ShelfIconChoice("⚾", "Baseball"),
    ShelfIconChoice("🎾", "Tennis"),
    ShelfIconChoice("🏐", "Volleyball"),
    ShelfIconChoice("🏉", "Rugby football"),
    ShelfIconChoice("🎱", "Pool 8 ball"),
    ShelfIconChoice("🏓", "Ping pong"),
    ShelfIconChoice("🏸", "Badminton"),
    ShelfIconChoice("🏒", "Ice hockey"),
    ShelfIconChoice("🥊", "Boxing glove"),
    ShelfIconChoice("🥋", "Martial arts uniform"),
    ShelfIconChoice("⛳", "Flag in hole"),
    ShelfIconChoice("⛷️", "Skier"),
    ShelfIconChoice("🏂", "Snowboarder"),
    ShelfIconChoice("🏋️", "Person lifting weights"),
    ShelfIconChoice("🤸", "Person cartwheeling"),
    ShelfIconChoice("🏆", "Trophy"),
    ShelfIconChoice("🥇", "1st place medal"),
    ShelfIconChoice("🥈", "2nd place medal"),
    ShelfIconChoice("🥉", "3rd place medal"),
    ShelfIconChoice("🎖️", "Military medal"),
    ShelfIconChoice("🎗️", "Reminder ribbon"),
    ShelfIconChoice("🎫", "Ticket"),
    ShelfIconChoice("🎪", "Circus tent"),
    ShelfIconChoice("🎭", "Performing arts"),
    ShelfIconChoice("🎨", "Artist palette"),
    ShelfIconChoice("🎬", "Clapper board"),
    ShelfIconChoice("🎤", "Microphone"),
    ShelfIconChoice("🎧", "Headphone"),
    ShelfIconChoice("🎼", "Musical score"),
    ShelfIconChoice("🎹", "Musical keyboard"),
    ShelfIconChoice("🥁", "Drum"),
    ShelfIconChoice("🎷", "Saxophone"),
    ShelfIconChoice("🎺", "Trumpet"),
    ShelfIconChoice("🎸", "Guitar"),
    ShelfIconChoice("🎻", "Violin"),
    ShelfIconChoice("🎲", "Game die"),
    ShelfIconChoice("🎯", "Direct hit"),
    ShelfIconChoice("🎳", "Bowling"),
    ShelfIconChoice("🎮", "Video game"),
    ShelfIconChoice("🎰", "Slot machine"),
    ShelfIconChoice("🧩", "Puzzle piece"),

    // Travel & places
    ShelfIconChoice("🚗", "Automobile"),
    ShelfIconChoice("🚕", "Taxi"),
    ShelfIconChoice("🚌", "Bus"),
    ShelfIconChoice("🏎️", "Racing car"),
    ShelfIconChoice("🚓", "Police car"),
    ShelfIconChoice("🚑", "Ambulance"),
    ShelfIconChoice("🚒", "Fire engine"),
    ShelfIconChoice("🚚", "Delivery truck"),
    ShelfIconChoice("🚲", "Bicycle"),
    ShelfIconChoice("🛵", "Motor scooter"),
    ShelfIconChoice("🏍️", "Motorcycle"),
    ShelfIconChoice("✈️", "Airplane"),
    ShelfIconChoice("🛫", "Airplane departure"),
    ShelfIconChoice("🚀", "Rocket"),
    ShelfIconChoice("🛸", "Flying saucer"),
    ShelfIconChoice("🚁", "Helicopter"),
    ShelfIconChoice("⛵", "Sailboat"),
    ShelfIconChoice("🚤", "Speedboat"),
    ShelfIconChoice("🚢", "Ship"),
    ShelfIconChoice("⚓", "Anchor"),
    ShelfIconChoice("🗺️", "World map"),
    ShelfIconChoice("🗽", "Statue of Liberty"),
    ShelfIconChoice("🗼", "Tokyo tower"),
    ShelfIconChoice("🏰", "Castle"),
    ShelfIconChoice("🎡", "Ferris wheel"),
    ShelfIconChoice("🎢", "Roller coaster"),
    ShelfIconChoice("🏖️", "Beach with umbrella"),
    ShelfIconChoice("🏝️", "Desert island"),
    ShelfIconChoice("🌋", "Volcano"),
    ShelfIconChoice("⛰️", "Mountain"),
    ShelfIconChoice("🏔️", "Snow-capped mountain"),
    ShelfIconChoice("⛺", "Tent"),
    ShelfIconChoice("🏠", "House"),
    ShelfIconChoice("🏡", "House with garden"),
    ShelfIconChoice("🏢", "Office building"),
    ShelfIconChoice("🏥", "Hospital"),
    ShelfIconChoice("🏫", "School"),
    ShelfIconChoice("⛪", "Church"),
    ShelfIconChoice("🕌", "Mosque"),
    ShelfIconChoice("🛕", "Hindu temple"),
    ShelfIconChoice("🌅", "Sunrise"),
    ShelfIconChoice("🌄", "Sunrise over mountains"),
    ShelfIconChoice("🌠", "Shooting star"),
    ShelfIconChoice("🎆", "Fireworks"),
    ShelfIconChoice("🎇", "Sparkler"),
    ShelfIconChoice("🌆", "Cityscape at dusk"),
    ShelfIconChoice("🌃", "Night with stars"),
    ShelfIconChoice("🌉", "Bridge at night"),

    // Objects
    ShelfIconChoice("⌚", "Watch"),
    ShelfIconChoice("📱", "Mobile phone"),
    ShelfIconChoice("💻", "Laptop"),
    ShelfIconChoice("⌨️", "Keyboard"),
    ShelfIconChoice("🖥️", "Desktop computer"),
    ShelfIconChoice("🖨️", "Printer"),
    ShelfIconChoice("🖱️", "Computer mouse"),
    ShelfIconChoice("🕹️", "Joystick"),
    ShelfIconChoice("📷", "Camera"),
    ShelfIconChoice("📹", "Video camera"),
    ShelfIconChoice("🎥", "Movie camera"),
    ShelfIconChoice("📞", "Telephone receiver"),
    ShelfIconChoice("☎️", "Telephone"),
    ShelfIconChoice("📺", "Television"),
    ShelfIconChoice("📻", "Radio"),
    ShelfIconChoice("🧭", "Compass"),
    ShelfIconChoice("⏱️", "Stopwatch"),
    ShelfIconChoice("⏰", "Alarm clock"),
    ShelfIconChoice("🕰️", "Mantelpiece clock"),
    ShelfIconChoice("⌛", "Hourglass done"),
    ShelfIconChoice("⏳", "Hourglass not done"),
    ShelfIconChoice("💡", "Light bulb"),
    ShelfIconChoice("🔦", "Flashlight"),
    ShelfIconChoice("🕯️", "Candle"),
    ShelfIconChoice("💰", "Money bag"),
    ShelfIconChoice("💵", "Dollar banknote"),
    ShelfIconChoice("💳", "Credit card"),
    ShelfIconChoice("💎", "Gem stone"),
    ShelfIconChoice("⚖️", "Balance scale"),
    ShelfIconChoice("🧰", "Toolbox"),
    ShelfIconChoice("🔧", "Wrench"),
    ShelfIconChoice("🔨", "Hammer"),
    ShelfIconChoice("⚙️", "Gear"),
    ShelfIconChoice("🔩", "Nut and bolt"),
    ShelfIconChoice("🧲", "Magnet"),
    ShelfIconChoice("🔫", "Water pistol"),
    ShelfIconChoice("🧨", "Firecracker"),
    ShelfIconChoice("🔪", "Kitchen knife"),
    ShelfIconChoice("🗡️", "Dagger"),
    ShelfIconChoice("⚔️", "Crossed swords"),
    ShelfIconChoice("🛡️", "Shield"),
    ShelfIconChoice("🔮", "Crystal ball"),
    ShelfIconChoice("📿", "Prayer beads"),
    ShelfIconChoice("🧿", "Nazar amulet"),
    ShelfIconChoice("🔭", "Telescope"),
    ShelfIconChoice("🔬", "Microscope"),
    ShelfIconChoice("💊", "Pill"),
    ShelfIconChoice("💉", "Syringe"),
    ShelfIconChoice("🧬", "DNA"),
    ShelfIconChoice("🌡️", "Thermometer"),
    ShelfIconChoice("🧹", "Broom"),
    ShelfIconChoice("🧺", "Basket"),
    ShelfIconChoice("🧻", "Roll of paper"),
    ShelfIconChoice("🚪", "Door"),
    ShelfIconChoice("🪑", "Chair"),
    ShelfIconChoice("🛏️", "Bed"),
    ShelfIconChoice("🛋️", "Couch and lamp"),
    ShelfIconChoice("🪞", "Mirror"),
    ShelfIconChoice("🛒", "Shopping cart"),
    ShelfIconChoice("🎁", "Wrapped gift"),
    ShelfIconChoice("🎀", "Ribbon"),
    ShelfIconChoice("🪄", "Magic wand"),
    ShelfIconChoice("🎈", "Balloon"),
    ShelfIconChoice("✉️", "Envelope"),
    ShelfIconChoice("📩", "Envelope with arrow"),
    ShelfIconChoice("📦", "Package"),
    ShelfIconChoice("🏷️", "Label"),
    ShelfIconChoice("📜", "Scroll"),
    ShelfIconChoice("📄", "Page facing up"),
    ShelfIconChoice("📊", "Bar chart"),
    ShelfIconChoice("📈", "Chart increasing"),
    ShelfIconChoice("📉", "Chart decreasing"),
    ShelfIconChoice("🗒️", "Spiral notepad"),
    ShelfIconChoice("🗓️", "Spiral calendar"),
    ShelfIconChoice("📆", "Tear-off calendar"),
    ShelfIconChoice("📅", "Calendar"),
    ShelfIconChoice("📇", "Card index"),
    ShelfIconChoice("📁", "File folder"),
    ShelfIconChoice("📂", "Open file folder"),
    ShelfIconChoice("🗞️", "Rolled-up newspaper"),
    ShelfIconChoice("📰", "Newspaper"),
    ShelfIconChoice("📓", "Notebook"),
    ShelfIconChoice("📔", "Notebook with decorative cover"),
    ShelfIconChoice("📒", "Ledger"),
    ShelfIconChoice("📕", "Closed book"),
    ShelfIconChoice("📗", "Green book"),
    ShelfIconChoice("📘", "Blue book"),
    ShelfIconChoice("📙", "Orange book"),
    ShelfIconChoice("📚", "Books"),
    ShelfIconChoice("📖", "Open book"),
    ShelfIconChoice("🔖", "Bookmark"),
    ShelfIconChoice("🔗", "Link"),
    ShelfIconChoice("📎", "Paperclip"),
    ShelfIconChoice("📐", "Triangular ruler"),
    ShelfIconChoice("📏", "Straight ruler"),
    ShelfIconChoice("🧮", "Abacus"),
    ShelfIconChoice("✂️", "Scissors"),
    ShelfIconChoice("🖊️", "Pen"),
    ShelfIconChoice("🖋️", "Fountain pen"),
    ShelfIconChoice("✒️", "Black nib"),
    ShelfIconChoice("🖌️", "Paintbrush"),
    ShelfIconChoice("🖍️", "Crayon"),
    ShelfIconChoice("📝", "Memo"),
    ShelfIconChoice("✏️", "Pencil"),
    ShelfIconChoice("🔍", "Magnifying glass tilted left"),
    ShelfIconChoice("🔒", "Locked"),
    ShelfIconChoice("🔓", "Unlocked"),
    ShelfIconChoice("🔑", "Key"),
    ShelfIconChoice("🗝️", "Old key"),

    // Symbols
    ShelfIconChoice("💯", "Hundred points"),
    ShelfIconChoice("💢", "Anger symbol"),
    ShelfIconChoice("💬", "Speech balloon"),
    ShelfIconChoice("💭", "Thought balloon"),
    ShelfIconChoice("🔴", "Red circle"),
    ShelfIconChoice("🟠", "Orange circle"),
    ShelfIconChoice("🟡", "Yellow circle"),
    ShelfIconChoice("🟢", "Green circle"),
    ShelfIconChoice("🔵", "Blue circle"),
    ShelfIconChoice("🟣", "Purple circle"),
    ShelfIconChoice("🟤", "Brown circle"),
    ShelfIconChoice("⚫", "Black circle"),
    ShelfIconChoice("⚪", "White circle"),
    ShelfIconChoice("🟥", "Red square"),
    ShelfIconChoice("🟧", "Orange square"),
    ShelfIconChoice("🟨", "Yellow square"),
    ShelfIconChoice("🟩", "Green square"),
    ShelfIconChoice("🟦", "Blue square"),
    ShelfIconChoice("🟪", "Purple square"),
    ShelfIconChoice("⬛", "Black large square"),
    ShelfIconChoice("⬜", "White large square"),
    ShelfIconChoice("🔶", "Large orange diamond"),
    ShelfIconChoice("🔷", "Large blue diamond"),
    ShelfIconChoice("🔺", "Red triangle pointed up"),
    ShelfIconChoice("🔻", "Red triangle pointed down"),
    ShelfIconChoice("💠", "Diamond with a dot"),
    ShelfIconChoice("🔘", "Radio button"),
    ShelfIconChoice("🚩", "Triangular flag"),
    ShelfIconChoice("🏁", "Chequered flag"),
)

val DEFAULT_SHELF_ICON: String = "📚"
